name: athlon_user
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  intl: ^0.19.0
  video_player: ^2.10.0
  font_awesome_flutter: ^10.6.0  # Added for better social login icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/findplay.jpg
    - assets/courts.jpg
    - assets/ark.jpg
    - assets/Athlon.png
    - assets/Athlon1.png
    - assets/cr7.jpg
    - assets/badminton.jpg
    - assets/crickett.jpg
    - assets/tennis.jpg
    - assets/basket.jpg
    - assets/football.jpg
    - assets/tabletennis.jpg
    - assets/netball.jpg