-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.booking_audit (
  audit_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  booking_id uuid NOT NULL,
  operation character varying NOT NULL,
  old_data jsonb,
  new_data jsonb,
  changed_by uuid,
  changed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT booking_audit_pkey PRIMARY KEY (audit_id)
);
CREATE TABLE public.bookings (
  customer_id uuid,
  facility_id uuid NOT NULL,
  customer_name text NOT NULL,
  customer_phone text NOT NULL,
  customer_email text,
  court_name text NOT NULL,
  court_type text NOT NULL,
  booking_date date NOT NULL,
  time_slot text NOT NULL,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone NOT NULL,
  duration integer NOT NULL,
  duration_hours numeric DEFAULT 1.0,
  price numeric NOT NULL,
  total_amount numeric NOT NULL,
  status text DEFAULT 'confirmed'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'cancelled'::text, 'completed'::text, 'occupied'::text, 'no_show'::text])),
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'paid'::text, 'refunded'::text, 'failed'::text])),
  payment_method text,
  special_requests text,
  booking_source text DEFAULT 'app'::text CHECK (booking_source = ANY (ARRAY['app'::text, 'website'::text, 'phone'::text, 'walk_in'::text])),
  check_in_time timestamp with time zone,
  check_out_time timestamp with time zone,
  cancellation_reason text,
  cancelled_by text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  maintenance_status text DEFAULT 'operational'::text CHECK (maintenance_status = ANY (ARRAY['operational'::text, 'maintenance'::text, 'blocked'::text, 'temporarily_closed'::text, 'suspended'::text])),
  maintenance_reason text,
  booking_blocked boolean NOT NULL DEFAULT false,
  court_id uuid NOT NULL,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.facilities(id),
  CONSTRAINT bookings_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT bookings_court_id_fkey FOREIGN KEY (court_id) REFERENCES public.courts(id)
);
CREATE TABLE public.bookings_backup (
  id text,
  customer_id uuid,
  facility_id uuid,
  court_id text,
  customer_name text,
  customer_phone text,
  customer_email text,
  court_name text,
  court_type text,
  booking_date date,
  time_slot text,
  start_time timestamp with time zone,
  end_time timestamp with time zone,
  duration integer,
  duration_hours numeric,
  price numeric,
  total_amount numeric,
  status text,
  payment_status text,
  payment_method text,
  special_requests text,
  booking_source text,
  check_in_time timestamp with time zone,
  check_out_time timestamp with time zone,
  cancellation_reason text,
  cancelled_by text,
  notes text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  maintenance_status text,
  maintenance_reason text,
  booking_blocked boolean
);
CREATE TABLE public.business_hours (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  is_open boolean DEFAULT true,
  opening_time time without time zone,
  closing_time time without time zone,
  break_start_time time without time zone,
  break_end_time time without time zone,
  is_24_hours boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT business_hours_pkey PRIMARY KEY (id),
  CONSTRAINT business_hours_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.chat_conversations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  vendor_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  last_message text,
  last_message_time timestamp with time zone DEFAULT now(),
  is_read_by_vendor boolean DEFAULT false,
  is_read_by_customer boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT chat_conversations_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT chat_conversations_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.chat_messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  conversation_id uuid NOT NULL,
  sender_type text NOT NULL CHECK (sender_type = ANY (ARRAY['vendor'::text, 'customer'::text])),
  sender_id uuid NOT NULL,
  message text NOT NULL,
  content text,
  time text,
  message_type text DEFAULT 'text'::text CHECK (message_type = ANY (ARRAY['text'::text, 'image'::text, 'file'::text])),
  is_read boolean DEFAULT false,
  is_sent_by_me boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.chat_conversations(id)
);
CREATE TABLE public.courts (
  facility_id uuid NOT NULL,
  name text NOT NULL,
  type text NOT NULL,
  hourly_rate numeric DEFAULT 0.00 CHECK (hourly_rate >= 0::numeric),
  is_active boolean DEFAULT true,
  is_blocked boolean NOT NULL DEFAULT false,
  description text,
  capacity integer DEFAULT 4,
  equipment_provided ARRAY,
  amenities ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  maintenance_status text DEFAULT 'operational'::text CHECK (maintenance_status = ANY (ARRAY['operational'::text, 'maintenance'::text, 'blocked'::text, 'temporarily_closed'::text, 'suspended'::text])),
  maintenance_reason text,
  last_maintenance_date date,
  booking_blocked boolean NOT NULL DEFAULT false,
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  CONSTRAINT courts_pkey PRIMARY KEY (id),
  CONSTRAINT courts_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.facilities(id)
);
CREATE TABLE public.courts_backup (
  id text,
  facility_id uuid,
  name text,
  type text,
  hourly_rate numeric,
  is_active boolean,
  is_blocked boolean,
  description text,
  capacity integer,
  equipment_provided ARRAY,
  amenities ARRAY,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  maintenance_status text,
  maintenance_reason text,
  last_maintenance_date date,
  booking_blocked boolean
);
CREATE TABLE public.customer_favorites (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  customer_id uuid NOT NULL,
  facility_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_favorites_pkey PRIMARY KEY (id),
  CONSTRAINT customer_favorites_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT customer_favorites_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.facilities(id)
);
CREATE TABLE public.customer_loyalty (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  customer_id uuid NOT NULL,
  facility_id uuid NOT NULL,
  program_id uuid NOT NULL,
  points_earned integer DEFAULT 0,
  points_redeemed integer DEFAULT 0,
  total_visits integer DEFAULT 0,
  total_spent numeric DEFAULT 0.00,
  tier_level text DEFAULT 'bronze'::text,
  last_activity timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_loyalty_pkey PRIMARY KEY (id),
  CONSTRAINT customer_loyalty_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT customer_loyalty_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.loyalty_programs(id),
  CONSTRAINT customer_loyalty_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.facilities(id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  phone text NOT NULL,
  email text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  profile_image_url text,
  location text,
  preferred_sports ARRAY,
  preferences jsonb DEFAULT '{}'::jsonb,
  loyalty_status jsonb,
  CONSTRAINT customers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.facilities (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  owner_id uuid NOT NULL,
  name text NOT NULL,
  location text NOT NULL,
  pending_bookings integer DEFAULT 0,
  today_bookings integer DEFAULT 0,
  total_courts integer DEFAULT 0,
  monthly_revenue numeric DEFAULT 0.00,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  booking_blocked boolean NOT NULL DEFAULT false,
  CONSTRAINT facilities_pkey PRIMARY KEY (id),
  CONSTRAINT facilities_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.facility_images (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  facility_id uuid NOT NULL,
  image_url text NOT NULL,
  image_type text DEFAULT 'general'::text CHECK (image_type = ANY (ARRAY['general'::text, 'court'::text, 'amenity'::text, 'exterior'::text, 'interior'::text])),
  caption text,
  alt_text text,
  display_order integer DEFAULT 0,
  is_primary boolean DEFAULT false,
  is_active boolean DEFAULT true,
  uploaded_by uuid,
  file_size integer,
  dimensions text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  court_id uuid,
  CONSTRAINT facility_images_pkey PRIMARY KEY (id),
  CONSTRAINT facility_images_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id),
  CONSTRAINT facility_images_court_id_fkey FOREIGN KEY (court_id) REFERENCES public.courts(id)
);
CREATE TABLE public.facility_images_backup (
  id uuid,
  facility_id uuid,
  court_id text,
  image_url text,
  image_type text,
  caption text,
  alt_text text,
  display_order integer,
  is_primary boolean,
  is_active boolean,
  uploaded_by uuid,
  file_size integer,
  dimensions text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone
);
CREATE TABLE public.loyalty_programs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  facility_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  type text NOT NULL CHECK (type = ANY (ARRAY['points'::text, 'visits'::text, 'spend'::text, 'subscription'::text])),
  rules jsonb NOT NULL,
  rewards jsonb NOT NULL,
  is_active boolean DEFAULT true,
  start_date date,
  end_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT loyalty_programs_pkey PRIMARY KEY (id),
  CONSTRAINT loyalty_programs_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.facilities(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  recipient_id uuid NOT NULL,
  sender_id uuid,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['booking'::text, 'payment'::text, 'reminder'::text, 'promotion'::text, 'system'::text, 'chat'::text, 'review'::text])),
  entity_type text,
  entity_id text,
  is_read boolean DEFAULT false,
  action_url text,
  push_sent boolean DEFAULT false,
  email_sent boolean DEFAULT false,
  priority text DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])),
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(id),
  CONSTRAINT notifications_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.pending_bookings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  facility_id uuid NOT NULL,
  court_id text NOT NULL,
  customer_name text NOT NULL,
  customer_phone text NOT NULL,
  customer_email text,
  creator text,
  sport text,
  match_type text,
  booking_date date NOT NULL,
  time_slot text NOT NULL,
  time_range text,
  duration_hours numeric DEFAULT 1.0,
  total_amount numeric NOT NULL,
  price text,
  player_count integer DEFAULT 1,
  equipment_needed ARRAY,
  special_requests text,
  preferred_court_features ARRAY,
  booking_source text DEFAULT 'app'::text,
  priority_level text DEFAULT 'normal'::text CHECK (priority_level = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])),
  notes text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'expired'::text])),
  processed_by uuid,
  processed_at timestamp with time zone,
  rejection_reason text,
  expires_at timestamp with time zone DEFAULT (now() + '24:00:00'::interval),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pending_bookings_pkey PRIMARY KEY (id),
  CONSTRAINT pending_bookings_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES public.profiles(id),
  CONSTRAINT pending_bookings_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.facilities(id)
);
CREATE TABLE public.pricing_rules (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  facility_id uuid NOT NULL,
  day_of_week integer CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone,
  end_time time without time zone,
  price numeric NOT NULL,
  rule_type text DEFAULT 'hourly'::text CHECK (rule_type = ANY (ARRAY['hourly'::text, 'peak'::text, 'off_peak'::text, 'weekend'::text, 'holiday'::text])),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  court_id uuid,
  CONSTRAINT pricing_rules_pkey PRIMARY KEY (id),
  CONSTRAINT pricing_rules_court_id_fkey FOREIGN KEY (court_id) REFERENCES public.courts(id)
);
CREATE TABLE public.pricing_rules_backup (
  id uuid,
  facility_id uuid,
  court_id text,
  day_of_week integer,
  start_time time without time zone,
  end_time time without time zone,
  price numeric,
  rule_type text,
  is_active boolean,
  created_at timestamp with time zone,
  updated_at timestamp with time zone
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  name text NOT NULL,
  phone text,
  facility_name text,
  user_type text DEFAULT 'vendor'::text CHECK (user_type = ANY (ARRAY['vendor'::text, 'customer'::text, 'admin'::text])),
  location text,
  full_address text,
  website text,
  opening_hours text,
  established text,
  status text,
  bio text,
  profile_image_url text,
  facilities_list ARRAY,
  services_list ARRAY,
  pricing_info jsonb,
  rating numeric DEFAULT 0.0 CHECK (rating >= 0.0 AND rating <= 5.0),
  review_count integer DEFAULT 0,
  is_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  timezone text DEFAULT 'Asia/Kolkata'::text,
  business_hours_display jsonb,
  amenities_list ARRAY,
  latitude numeric,
  longitude numeric,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  facility_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text,
  service_rating integer CHECK (service_rating >= 1 AND service_rating <= 5),
  facility_rating integer CHECK (facility_rating >= 1 AND facility_rating <= 5),
  value_rating integer CHECK (value_rating >= 1 AND value_rating <= 5),
  cleanliness_rating integer CHECK (cleanliness_rating >= 1 AND cleanliness_rating <= 5),
  review_title text,
  pros ARRAY,
  cons ARRAY,
  would_recommend boolean DEFAULT true,
  photos ARRAY,
  is_verified boolean DEFAULT false,
  response_from_vendor text,
  response_date timestamp with time zone,
  is_featured boolean DEFAULT false,
  helpful_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  booking_id uuid,
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT reviews_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.facilities(id),
  CONSTRAINT reviews_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.time_slots (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  slot_date date NOT NULL,
  time_slot text NOT NULL,
  status text DEFAULT 'available'::text CHECK (status = ANY (ARRAY['available'::text, 'occupied'::text, 'selected'::text, 'blocked'::text, 'maintenance'::text])),
  price numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  maintenance_reason text,
  court_id uuid NOT NULL,
  booking_id uuid,
  CONSTRAINT time_slots_pkey PRIMARY KEY (id),
  CONSTRAINT time_slots_court_id_fkey FOREIGN KEY (court_id) REFERENCES public.courts(id),
  CONSTRAINT time_slots_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.time_slots_backup (
  id uuid,
  court_id text,
  slot_date date,
  time_slot text,
  status text,
  booking_id text,
  price numeric,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  maintenance_reason text
);